name: spacex
description: "A SpaceX Api Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_bloc: ^8.1.2
  i69n: ^2.1.0
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  intl: ^0.19.0
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  top_snackbar_flutter: ^3.2.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: any
  mockito: any
  bloc_test: any
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
